---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: bazarr
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/bazarr
      tag: v0.9.6
    env:
      TZ: "Europe/London"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "bazarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "bazarr.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "bazarr.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "bazarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    additionalVolumeMounts:
    - name: tv-nfs
      mountPath: /data/tv
    - name: movies-nfs
      mountPath: /data/movies
    additionalVolumes:
    - name: tv-nfs
      nfs:
        server: 192.168.1.240
        path: /mnt/data/media/tv
    - name: movies-nfs
      nfs:
        server: 192.168.1.240
        path: /mnt/data/media/movies
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
